### ISSUE TITLE
Document and extend / test SSE

### ISSUE THREAD

**Issue by nixpulvis** [Americastestkitchen/metricution#3]
This module is pretty cool, but needs testing and should be sure it covers the full SSE protocol.

**Comment by nixpulvis** [comment]
Hi patrick.

**Comment by phereford** [comment]
hehehe. Hey Nate ;)

**Comment by nixpulvis** [comment]
Holy shit you're up late (or early, ugh this 3 hour time change).

GitHub chat, ftw.

**Comment by pherefordATK** [comment]
:P. How goes sunny CA?

On Thu, Aug 27, 2015 at 6:59 AM, Nathan Lilienthal <notifications@github.com
